import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.sass";
import Link from "next/link";
import { useEffect, useState, useContext } from "react";
import { AuthContext } from "@/context/AuthContext";

export default function Home() {
  const {handleLogin} = useContext(AuthContext)
  
  return (
    <>
      <Head>
        <title>Google 驗證範例</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>主頁</h1>
        {/* <div className={styles.commonBtn} onClick={handleLogin}>驗證</div><br /> */}
        <Link className={styles.commonBtn} href="/page1">需要驗證的頁面1</Link><br />
        <Link className={styles.commonBtn} href="/page2">需要驗證的頁面2</Link><br />
        <Link className={styles.commonBtn} href="/page3">不需要驗證的頁面</Link>
      </main>
    </>
  );
}
