import Head from "next/head";
import styles from "@/styles/Home.module.sass";
import Link from "next/link";
import { useContext } from "react";
import { AuthContext } from "@/context/AuthContext";

const Login = () => {
  const {handleLogin} = useContext(AuthContext);
  return (
    <>
      <Head>
        <title>登入頁</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>登入頁</h1>
        <div className={styles.commonBtn} onClick={handleLogin}>驗證</div><br />
        <Link className={styles.commonBtn} href="/">首頁</Link>
      </main>
    </>
  );
}
export default Login;