import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.sass";
import Link from "next/link";

export default function Page3() {
  return (
    <>
      <Head>
        <title>不需要驗證的頁面</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>不需要驗證的頁面</h1>
        <Link className={styles.commonBtn} href="/">回主頁</Link><br />
      </main>
    </>
  );
}
