import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.sass";
import Link from "next/link";
import { useContext } from "react";
import { AuthContext } from "@/context/AuthContext";

export default function Page2() {
  const {user, handleLogout} = useContext(AuthContext);
  return (
    <>
      <Head>
        <title>需要驗證的頁面2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>需要驗證的頁面2</h1>
        {user && (
          <>
            <div>{user.name}</div>
            <div>{user.email}</div>
            <div className={styles.commonBtn} onClick={handleLogout}>登出</div>
          </>
        )}
        <Link className={styles.commonBtn} href="/">回主頁</Link><br />
      </main>
    </>
  );
}
